params_bounds_max:
- 100000.0
- -8
- 0.01
- 0.01
- 5
params_bounds_min:
- 0
- -25
- -0.01
- -0.01
- -5
params_excluded:
- 0
- 1
- 2
- 3
- 4
params_fixed:
- 1.0
- -8
- 0
- 0
- 0
params_init:
- 0.1
- -15
- 0
- 0
- 0
